### ISSUE TITLE
Make non nullable fields required in Swagger

### ISSUE THREAD

**Issue by ffMathy** [sponsorkit/sponsorkit.io#10]
See https://github.com/Azure/autorest.typescript/issues/994#issuecomment-857828396

**Comment by sarangan12** [comment]
@ffMathy I have updated the comment to include the correct property. It is not x-nullable. It is `required`. Please refer the comment https://github.com/Azure/autorest.typescript/issues/994#issuecomment-857828396 for details.

**Comment by ffMathy** [comment]
Wow @sarangan12 thank you for coming over here and reporting that! 👌🙏
