### ISSUE TITLE
Investigate currency conversion

### ISSUE THREAD

**Issue by ffMathy** [sponsorkit/sponsorkit.io#7]
Right now, the Stripe fee is in DKK, but the charge is in USD. What happens to the fee then? How do we ensure we collect enough, if currency rates change?

**Comment by ffMathy** [comment]
Idea: Charge in DKK.

**Comment by ffMathy** [comment]
Idea: Auth on bounty creation, re-auth and capture on bounty awarding. Perhaps even auth regularly to see if bounty is still valid.

**Comment by ffMathy** [comment]
Idea: Charge fees up front, including potential currency exchange fee.

**Comment by tarangan** [comment]
is bounty on

**Comment by ffMathy** [comment]
@tarangan no, but soon, many of these issues will have bounties on them! 🙏

Watch this repository to stay up to date. https://bountyhunt.io will launch soon.

Do you want me to remind you when it is ready and launched?

Also, can I ask how you found the project? 😊🙏
